# 넘파이


In [1]:
import numpy as np
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

In [4]:
array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(3,)


In [5]:
array2 = np.array([[1,2,3], [2,3,4]])
print(type(array2))
print(array2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [6]:
array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(1, 3)


In [9]:
print(array3.ndim)

2


In [14]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [17]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
array_int1 = array_float.astype('int32')
print(array_float, array_float.dtype)
print(array_int1, array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


# ndarray를 편리하게 생성하기 - arange, zeros, ones

In [20]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.shape, sequence_array.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,) int32


In [23]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape()

In [27]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(2, 5)
print(array2)
array3 = array1.reshape(5, 2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [28]:
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [32]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print(array2)
array3 = array1.reshape(5, -1)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [41]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())
print()

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)
print()

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)
## 1. 특정한 데이터만 추출: 원하는 위치의 인덱스값을 지정하면 해당 위치의 데이터가 반환됩니다.
## 2. 슬라이싱
## 3. 팬시 인덱싱: 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환합니다.
## 4. 불린 인덱싱: 특정 조건에 해당하는 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환합니다.

# 1. 단일추출

In [45]:
array1 = np.arange(start = 1, stop = 10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [47]:
value = array1[2]
print(value)
print(type(value))

3
<class 'numpy.int32'>


In [50]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


# 2. 슬라이싱

In [51]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


# 3. 팬시 인덱싱

In [67]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d.tolist())
print()

array3 = array2d[[0, 1]]
print(array3.tolist())
print()

array4 = array2d[[0, 1], 0:2]
print(array4.tolist())
print()

array5 = array2d[[0,1]]
print(array5.tolist())

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1, 2, 3], [4, 5, 6]]

[[1, 2], [4, 5]]

[[1, 2, 3], [4, 5, 6]]


# 4. 불린 인덱싱

In [68]:
array1d = np.arange(start=1, stop = 10)
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [69]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [71]:
boolen_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolen_indexes]

print(array3)

[6 7 8 9]


# 행렬 정렬

In [15]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort()이용
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
print()

# ndarray.sort()이용
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환 된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)
print()

# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print("내림차순 정렬:",sort_array1_desc)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]

org_array.sort() 호출 후 반환 된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]

내림차순 정렬: [9 5 3 1]


In [22]:
# 행렬이 2차원 이상일 경우 로우, 컬럼방향 기준으로 정렬하기
array2d = np.array([[8, 12],
                    [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방량으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print("컬럼 방향으로 정렬:\n", sort_array2d_axis1)

로우 방량으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


# 정렬된 행렬의 인덱스를 반환하기

In [30]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print("행렬 정렬 시 원본 행렬의 인덱스:",sort_indices) # 가장 작은 인덱스부터 큰 순서대로 나와있다.
print(type(sort_indices))

행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
<class 'numpy.ndarray'>


In [31]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스:", sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [33]:
import numpy as np
name_array = np.array(["Jo", "Mi", "Sa", "Ka", "Sam"])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print("성적 오름차순 정렬 시 score_array의 인덱스:", sort_indices_asc)
print("성적 오름차순으로 name_array의 이름 출력:", name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['Jo' 'Sa' 'Sam' 'Mi' 'Ka']


# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

## 행렬 내적(행렬 곱)

In [40]:
A = np.array([[1,2,3],
              [4, 5, 6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

print(np.dot(A,B))
print()
print(np.dot(B,A))

[[ 58  64]
 [139 154]]

[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


## 전치 행렬

In [38]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print("A의 전치 행렬:\n", transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
